### ISSUE TITLE
Signup Page Issue (Typo and blood stock issue) 

### ISSUE THREAD

**Issue by mmnauman** [UdacityFrontEndScholarship/jeevan-rakht#184]
Hello, when we submitted the signup forum with the weak password we are getting the validation error that has typo mistakes.  like it should be contain but it is written contail fix it.

One more confusion bloodstock in litres or bottles please mention it this is confusing for anyone. and why it is reaching the negative number.

![github issue](https://user-images.githubusercontent.com/23205151/39672323-c4a7f6d0-5145-11e8-994f-a625252dcfaf.JPG)
?

**Comment by gauravsinghaec** [comment]
Thanks buddy, check if you find more. We will update it.

**Comment by Logan1x** [comment]
@gauravsinghaec typo in sign  up page updated and not able to find where I can update `Blood stock` to update in lit or bottle's

**Comment by Logan1x** [comment]
> not able to find where I can update Blood stock to update in lit or bottle's

Done 

now if someone tell me how to make its value only positive?

**Comment by gauravsinghaec** [comment]
@mmnauman can you please help @Logan1x

**Comment by Logan1x** [comment]
thanks, @nsaicharan updating.

**Comment by Logan1x** [comment]
@gauravsinghaec  please review #188

**Comment by mmnauman** [comment]
Still, Blood Stock is not fixed. What we need to do is just add another input type select and in that, we have to add litres, bottles etc .

**Comment by Logan1x** [comment]
> Blood Stock is not fixed

PR is in the process will be add soon.

**Comment by gauravsinghaec** [comment]
@mmnauman and @Logan1x @nsaicharan kudos to all of you. 🥇 
The issue is resolved now.
